// Fictional sample community. Every person here is invented.
// The set is chosen to exercise every state in the product: Free and Premium,
// new and established members, enough / not enough feedback, active Primaries,
// waiting lists, long-distance, friendship, and a romance that became friendship.

import { TRAITS } from './trust';
import type {
  Connection,
  FeedbackEntry,
  Gender,
  History,
  Interest,
  Kind,
  Message,
  Place,
  Portrait,
  Profile,
  Settings,
  State,
  Trait,
  User,
  VerificationKey,
} from './types';

const DAY = 86_400_000;
export const STATE_VERSION = 4;

// ---------------------------------------------------------------------------
// Places
// ---------------------------------------------------------------------------

const P = {
  gurgaon: { city: 'Gurgaon', metro: 'Delhi NCR', region: 'North India', country: 'India' },
  delhi: { city: 'Delhi', metro: 'Delhi NCR', region: 'North India', country: 'India' },
  noida: { city: 'Noida', metro: 'Delhi NCR', region: 'North India', country: 'India' },
  chandigarh: { city: 'Chandigarh', metro: 'Chandigarh Tricity', region: 'North India', country: 'India' },
  jaipur: { city: 'Jaipur', metro: 'Jaipur', region: 'North India', country: 'India' },
  mumbai: { city: 'Mumbai', metro: 'Mumbai', region: 'West India', country: 'India' },
  pune: { city: 'Pune', metro: 'Pune', region: 'West India', country: 'India' },
  bengaluru: { city: 'Bengaluru', metro: 'Bengaluru', region: 'South India', country: 'India' },
  mysuru: { city: 'Mysuru', metro: 'Mysuru', region: 'South India', country: 'India' },
  chennai: { city: 'Chennai', metro: 'Chennai', region: 'South India', country: 'India' },
  london: { city: 'London', metro: 'London', region: 'England', country: 'United Kingdom' },
  toronto: { city: 'Toronto', metro: 'Toronto', region: 'Ontario', country: 'Canada' },
  dubai: { city: 'Dubai', metro: 'Dubai', region: 'Dubai', country: 'United Arab Emirates' },
  singapore: { city: 'Singapore', metro: 'Singapore', region: 'Singapore', country: 'Singapore' },
  lisbon: { city: 'Lisbon', metro: 'Lisbon', region: 'Lisbon', country: 'Portugal' },
} satisfies Record<string, Place>;

export const COUNTRIES = [
  'India',
  'United Kingdom',
  'Canada',
  'Australia',
  'United Arab Emirates',
  'Singapore',
  'United States',
  'Portugal',
];

// ---------------------------------------------------------------------------
// Portrait palettes (muted, editorial)
// ---------------------------------------------------------------------------

const TONES: [string, string, string][] = [
  ['#EADCCB', '#C7A487', '#4E3B2E'],
  ['#DCE1D6', '#9DAE97', '#34402F'],
  ['#E8D8D2', '#BD978D', '#533937'],
  ['#D9DEE5', '#97A4B4', '#333C49'],
  ['#ECE1CB', '#CCAE77', '#54431F'],
  ['#DED6E2', '#A594AE', '#3F3446'],
  ['#D6E0DE', '#8FAAA6', '#2C403D'],
  ['#E9DCD6', '#C99B82', '#5A3A2A'],
];

function portraits(seed: number, gender: Gender): Portrait[] {
  const base: Portrait['variant'][] = gender === 'man' ? [2, 3] : gender === 'woman' ? [0, 1] : [1, 2];
  return [0, 1, 2].map((i) => {
    const [from, to, ink] = TONES[(seed + i * 3) % TONES.length];
    return { from, to, ink, variant: base[(seed + i) % 2] };
  });
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

interface Spec {
  id: string;
  name: string;
  age: number;
  gender: Gender;
  seeking?: Gender[];
  place: Place;
  profession: string;
  education?: string;
  bio: string;
  intent: Profile['intent'];
  intentNext?: Profile['intentNext'];
  lifestyle: string[];
  interests: string[];
  values: string[];
  languages: string[];
  future?: Profile['future'];
  prompt?: Profile['prompt'];
  openTo?: Kind[];
  plan?: User['plan'];
  verified?: VerificationKey[];
  settings?: Partial<Settings>;
  since: number; // days ago
  history?: Partial<Omit<History, 'memberSince'>>;
  persona?: string;
}

const defaultSettings: Settings = {
  feedbackVisible: true,
  incognito: false,
  anonymousDiscovery: false,
  discoveryPaused: false,
  reach: 'regional',
  countries: [],
  longDistance: false,
  relocation: false,
  international: false,
  sharing: { profession: 'discovery', education: 'discovery', future: 'mutual', languages: 'discovery' },
  filters: { minAge: 21, maxAge: 45, verifiedOnly: false, intents: [] },
};

let seedIndex = 0;

function person(spec: Spec, now: number): User {
  const iso = (daysAgo: number) => new Date(now - daysAgo * DAY).toISOString();
  const verification = Object.fromEntries(
    (['identity', 'phone', 'photo', 'employment', 'education', 'profile'] as VerificationKey[]).map((k) => [
      k,
      (spec.verified ?? ['phone']).includes(k),
    ]),
  ) as Record<VerificationKey, boolean>;
  return {
    id: spec.id,
    plan: spec.plan ?? 'free',
    verification,
    persona: spec.persona ? { tagline: spec.persona } : undefined,
    profile: {
      firstName: spec.name,
      age: spec.age,
      gender: spec.gender,
      seeking: spec.seeking ?? (spec.gender === 'man' ? ['woman'] : spec.gender === 'woman' ? ['man'] : ['woman', 'man', 'nonbinary']),
      place: spec.place,
      profession: spec.profession,
      education: spec.education,
      bio: spec.bio,
      intent: spec.intent,
      intentNext: spec.intentNext,
      lifestyle: spec.lifestyle,
      interests: spec.interests,
      values: spec.values,
      languages: spec.languages,
      future: spec.future ?? {},
      prompt: spec.prompt,
      portraits: portraits(seedIndex++, spec.gender),
      openTo: spec.openTo ?? (spec.intent === 'friendship' ? ['friendship'] : ['romantic']),
    },
    settings: { ...defaultSettings, ...spec.settings },
    history: {
      memberSince: iso(spec.since),
      meaningfulInteractions: 0,
      mutualConnections: 0,
      completedConversations: 0,
      meetings: 0,
      movedToFriendship: 0,
      durations: [],
      beyondInitialPct: 0,
      toMeetingPct: 0,
      changes: {},
      ...spec.history,
    },
  };
}

// ---------------------------------------------------------------------------
// People
// ---------------------------------------------------------------------------

function people(now: number): User[] {
  const ago = (d: number) => new Date(now - d * DAY).toISOString();
  seedIndex = 0;
  const specs: Spec[] = [
    // ---- Personas you can explore as -------------------------------------
    {
      id: 'abhishek',
      name: 'Abhishek',
      age: 31,
      gender: 'man',
      place: P.gurgaon,
      profession: 'Strategy consultant',
      education: 'IIM Bangalore',
      bio: "I grew up between Lucknow and Delhi and still can't pick a favourite. Weekdays are spreadsheets and client calls; weekends are long drives, old Hindi film songs and trying to cook my mother's rajma without calling her.",
      intent: 'serious',
      intentNext: 'marriage',
      lifestyle: ['Early riser', 'Runs on weekends', 'Social drinker', 'Vegetarian'],
      interests: ['Travel', 'Music', 'Reading', 'Cooking'],
      values: ['Honesty', 'Family', 'Curiosity'],
      languages: ['Hindi', 'English'],
      future: {
        marriageTimeline: 'In 1–2 years',
        children: 'Wants children',
        relocation: 'Open to relocating',
        career: 'Both partners working',
        family: 'Close to family, independent household',
        finances: 'Shared, with personal independence',
        culture: 'Open to all backgrounds',
        longTermGoals: 'A calm home, a few good friends, and a year abroad at some point.',
      },
      prompt: { q: 'A perfect Sunday', a: 'Parathas, a long walk in Lodhi Garden, and an unhurried phone call with my grandmother.' },
      openTo: ['romantic', 'friendship'],
      plan: 'premium',
      verified: ['identity', 'phone', 'photo', 'employment', 'profile'],
      settings: {
        reach: 'international',
        countries: ['United Kingdom', 'Canada', 'Singapore', 'United Arab Emirates'],
        longDistance: true,
        relocation: true,
        international: true,
      },
      since: 620,
      history: {
        meaningfulInteractions: 31,
        mutualConnections: 14,
        completedConversations: 11,
        meetings: 5,
        movedToFriendship: 2,
        durations: [9, 21, 14, 3, 40, 18, 12, 26, 7, 33],
        beyondInitialPct: 71,
        toMeetingPct: 36,
        changes: { photos: ago(61), location: ago(410), intent: ago(95) },
      },
      persona: 'Premium · dating Ananya · 4 people waiting',
    },
    {
      id: 'meera',
      name: 'Meera',
      age: 27,
      gender: 'woman',
      place: P.bengaluru,
      profession: 'UX researcher',
      education: 'NID Ahmedabad',
      bio: 'I ask people questions for a living and I am still curious about everyone. Filter coffee loyalist, reluctant runner, and the friend who always has a book recommendation.',
      intent: 'long-term',
      lifestyle: ['Night owl', 'Doesn’t drink', 'Pet lover', 'Yoga'],
      interests: ['Reading', 'Theatre', 'Hiking', 'Coffee'],
      values: ['Kindness', 'Curiosity', 'Independence'],
      languages: ['Kannada', 'Tamil', 'English'],
      future: {
        marriageTimeline: 'In 2–3 years',
        children: 'Open to children',
        relocation: 'Prefers to stay in Bengaluru',
        career: 'Both partners working',
        family: 'Close to family, independent household',
      },
      prompt: { q: 'I’m looking for', a: 'Someone who reads the room and the menu with equal care.' },
      openTo: ['romantic', 'friendship'],
      plan: 'free',
      verified: ['phone', 'photo'],
      settings: { reach: 'local' },
      since: 18,
      history: { meaningfulInteractions: 1, mutualConnections: 1 },
      persona: 'Free · new member · slot open',
    },
    {
      id: 'sarah',
      name: 'Sarah',
      age: 30,
      gender: 'woman',
      place: P.london,
      profession: 'Architect',
      education: 'The Bartlett, UCL',
      bio: 'Half Keralite, half Londoner, fully obsessed with good light. I design libraries, cycle everywhere and spend my winters planning my next trip to Kochi.',
      intent: 'serious',
      lifestyle: ['Cycles to work', 'Social drinker', 'Early riser'],
      interests: ['Travel', 'Design', 'Music', 'Swimming'],
      values: ['Honesty', 'Independence', 'Humour'],
      languages: ['English', 'Malayalam'],
      future: {
        marriageTimeline: 'In 1–2 years',
        children: 'Wants children',
        relocation: 'Open to relocating',
        career: 'Both partners working',
        family: 'Close to family, independent household',
      },
      plan: 'premium',
      verified: ['identity', 'phone', 'photo', 'education'],
      settings: {
        feedbackVisible: false,
        reach: 'global',
        international: true,
        relocation: true,
        longDistance: true,
      },
      since: 140,
      history: {
        meaningfulInteractions: 6,
        mutualConnections: 4,
        completedConversations: 3,
        meetings: 1,
        durations: [11, 6, 19],
        beyondInitialPct: 60,
        toMeetingPct: 25,
        changes: { photos: ago(20), location: ago(140) },
      },
      persona: 'Premium · feedback hidden · London',
    },

    // ---- Abhishek's world -------------------------------------------------
    {
      id: 'ananya',
      name: 'Ananya',
      age: 29,
      gender: 'woman',
      place: P.gurgaon,
      profession: 'Product designer',
      education: 'Srishti, Bengaluru',
      bio: 'I design banking apps by day and bad watercolours by night. I love slow mornings, strong chai, and people who say what they mean. Recently learning to be okay with not having a five-year plan.',
      intent: 'serious',
      intentNext: 'marriage',
      lifestyle: ['Early riser', 'Yoga', 'Social drinker', 'Vegetarian'],
      interests: ['Travel', 'Music', 'Reading', 'Painting'],
      values: ['Honesty', 'Family', 'Kindness'],
      languages: ['Hindi', 'English', 'Bengali'],
      future: {
        marriageTimeline: 'In 1–2 years',
        children: 'Wants children',
        relocation: 'Prefers to stay in NCR',
        career: 'Both partners working',
        family: 'Close to family, independent household',
        finances: 'Shared, with personal independence',
      },
      prompt: { q: 'What matters to me', a: 'Being taken seriously, being made to laugh, and Sunday phone calls with my nani.' },
      plan: 'free',
      verified: ['identity', 'phone', 'photo', 'employment'],
      since: 560,
      history: {
        meaningfulInteractions: 47,
        mutualConnections: 23,
        completedConversations: 18,
        meetings: 6,
        movedToFriendship: 3,
        durations: [18, 11, 2, 94, 14, 9, 22, 11, 30, 7, 16, 5, 25, 8, 12, 19, 10, 13],
        beyondInitialPct: 68,
        toMeetingPct: 33,
        changes: { photos: ago(34), location: ago(300), intent: ago(120) },
      },
    },
    {
      id: 'rahul',
      name: 'Rahul',
      age: 32,
      gender: 'man',
      place: P.delhi,
      profession: 'Documentary editor',
      bio: 'Cuts films for a living, cuts vegetables badly. Looking for a friend to try every biryani in Old Delhi with and argue about cricket.',
      intent: 'friendship',
      lifestyle: ['Night owl', 'Plays football', 'Social drinker'],
      interests: ['Film', 'Cricket', 'Food', 'Music'],
      values: ['Loyalty', 'Humour'],
      languages: ['Hindi', 'Punjabi', 'English'],
      openTo: ['friendship'],
      verified: ['identity', 'phone', 'photo'],
      since: 300,
      history: {
        meaningfulInteractions: 12,
        mutualConnections: 7,
        completedConversations: 5,
        meetings: 4,
        durations: [30, 60, 12, 45],
        beyondInitialPct: 80,
        toMeetingPct: 57,
      },
    },
    {
      id: 'priya',
      name: 'Priya',
      age: 29,
      gender: 'woman',
      place: P.gurgaon,
      profession: 'Chartered accountant',
      education: 'SRCC, Delhi',
      bio: 'Numbers at work, stories at home. I read a novel a week, bake when stressed and take my Saturday morning badminton very seriously.',
      intent: 'marriage',
      lifestyle: ['Early riser', 'Plays badminton', 'Doesn’t drink'],
      interests: ['Reading', 'Baking', 'Travel'],
      values: ['Family', 'Honesty'],
      languages: ['Hindi', 'English', 'Marwari'],
      future: { marriageTimeline: 'In 1–2 years', children: 'Wants children', family: 'Joint family is fine' },
      plan: 'free',
      verified: ['identity', 'phone', 'photo', 'employment', 'education'],
      since: 400,
      history: {
        meaningfulInteractions: 19,
        mutualConnections: 9,
        completedConversations: 7,
        meetings: 3,
        movedToFriendship: 1,
        durations: [20, 15, 8, 41, 12],
        beyondInitialPct: 74,
        toMeetingPct: 38,
        changes: { photos: ago(80) },
      },
    },
    {
      id: 'riya',
      name: 'Riya',
      age: 28,
      gender: 'woman',
      place: P.delhi,
      profession: 'Journalist',
      bio: 'I cover climate for a national daily and I will absolutely ask you about your carbon footprint on the first date. Kidding. Mostly.',
      intent: 'long-term',
      lifestyle: ['Night owl', 'Social drinker', 'Cycles'],
      interests: ['Music', 'Politics', 'Hiking', 'Travel'],
      values: ['Curiosity', 'Honesty'],
      languages: ['Hindi', 'English'],
      future: { children: 'Open to children', relocation: 'Open to relocating' },
      verified: ['phone', 'photo'],
      settings: { relocation: true },
      since: 45,
      history: {
        meaningfulInteractions: 3,
        mutualConnections: 2,
        completedConversations: 1,
        durations: [6],
        beyondInitialPct: 50,
      },
    },
    {
      id: 'neha',
      name: 'Neha',
      age: 27,
      gender: 'woman',
      place: P.mumbai,
      profession: 'Doctor (resident)',
      education: 'KEM Hospital, Mumbai',
      bio: 'Paediatrics resident. My shifts are long, so I value people who are patient and a little bit silly. I dance in my kitchen at 2am after nights.',
      intent: 'serious',
      lifestyle: ['Irregular hours', 'Doesn’t drink', 'Dances'],
      interests: ['Dance', 'Music', 'Travel'],
      values: ['Kindness', 'Family'],
      languages: ['Marathi', 'Hindi', 'English'],
      future: { marriageTimeline: 'In 2–3 years', children: 'Wants children', relocation: 'Open to relocating' },
      plan: 'premium',
      verified: ['identity', 'phone', 'photo', 'employment', 'education'],
      settings: { longDistance: true, relocation: true, reach: 'national' },
      since: 330,
      history: {
        meaningfulInteractions: 14,
        mutualConnections: 8,
        completedConversations: 6,
        meetings: 2,
        durations: [10, 25, 13, 4, 17],
        beyondInitialPct: 66,
        toMeetingPct: 25,
      },
    },
    {
      id: 'kabir',
      name: 'Kabir',
      age: 30,
      gender: 'man',
      place: P.gurgaon,
      profession: 'Architect',
      bio: 'New to Gurgaon, looking for people to run with on Sunday mornings and to talk about buildings nobody else notices.',
      intent: 'friendship',
      lifestyle: ['Early riser', 'Runs on weekends'],
      interests: ['Running', 'Design', 'Reading'],
      values: ['Curiosity'],
      languages: ['Hindi', 'English'],
      openTo: ['friendship'],
      verified: ['phone', 'photo'],
      since: 60,
      history: { meaningfulInteractions: 2, mutualConnections: 2 },
    },
    {
      id: 'tara',
      name: 'Tara',
      age: 29,
      gender: 'woman',
      place: P.delhi,
      profession: 'Museum curator',
      bio: 'I spend my days with 18th-century miniatures and my evenings with jazz. Wonderful company, bad at replying to texts, great in person.',
      intent: 'exploring',
      lifestyle: ['Night owl', 'Social drinker'],
      interests: ['Art', 'Music', 'Reading', 'Travel'],
      values: ['Curiosity', 'Humour'],
      languages: ['Hindi', 'English', 'Urdu'],
      openTo: ['romantic', 'friendship'],
      verified: ['identity', 'phone', 'photo', 'employment'],
      since: 250,
      history: {
        meaningfulInteractions: 11,
        mutualConnections: 6,
        completedConversations: 4,
        meetings: 3,
        movedToFriendship: 2,
        durations: [28, 9, 15, 21],
        beyondInitialPct: 70,
        toMeetingPct: 50,
      },
    },
    {
      id: 'ishaan',
      name: 'Ishaan',
      age: 26,
      gender: 'man',
      place: P.noida,
      profession: 'Software engineer',
      bio: 'Board games, badminton, and the occasional very ambitious trek. Looking for friends who show up.',
      intent: 'friendship',
      lifestyle: ['Plays badminton', 'Gamer'],
      interests: ['Board games', 'Trekking', 'Music'],
      values: ['Loyalty'],
      languages: ['Hindi', 'English'],
      openTo: ['friendship'],
      verified: ['phone'],
      since: 9,
    },
    {
      id: 'mansi',
      name: 'Mansi',
      age: 30,
      gender: 'woman',
      place: P.delhi,
      profession: 'Policy researcher',
      bio: 'Think tanks by day, thriller novels by night.',
      intent: 'long-term',
      lifestyle: ['Early riser', 'Yoga'],
      interests: ['Reading', 'Travel', 'Politics'],
      values: ['Honesty'],
      languages: ['Hindi', 'English'],
      verified: ['identity', 'phone', 'photo'],
      settings: { discoveryPaused: true },
      since: 200,
      history: { meaningfulInteractions: 8, mutualConnections: 5, completedConversations: 3, meetings: 1, durations: [12, 8, 23] },
    },

    // ---- Discovery pool: Delhi NCR & North India --------------------------
    {
      id: 'kavya',
      name: 'Kavya',
      age: 30,
      gender: 'woman',
      place: P.noida,
      profession: 'Paediatrician',
      education: 'AIIMS, New Delhi',
      bio: 'Doctor, amateur birdwatcher, and the person at the party who ends up in the kitchen talking to someone’s grandmother. I want a partnership where we both keep growing.',
      intent: 'marriage',
      lifestyle: ['Early riser', 'Vegetarian', 'Doesn’t drink'],
      interests: ['Birdwatching', 'Travel', 'Reading', 'Music'],
      values: ['Family', 'Kindness', 'Honesty'],
      languages: ['Hindi', 'English', 'Telugu'],
      future: {
        marriageTimeline: 'In 1–2 years',
        children: 'Wants children',
        relocation: 'Open to relocating',
        family: 'Close to family, independent household',
      },
      prompt: { q: 'Green flags', a: 'You’re kind to waiters and you know when to put your phone away.' },
      openTo: ['romantic', 'friendship'],
      plan: 'premium',
      verified: ['identity', 'phone', 'photo', 'employment', 'education', 'profile'],
      settings: { relocation: true },
      since: 510,
      history: {
        meaningfulInteractions: 24,
        mutualConnections: 12,
        completedConversations: 9,
        meetings: 7,
        movedToFriendship: 2,
        durations: [15, 31, 12, 8, 44, 19, 22],
        beyondInitialPct: 75,
        toMeetingPct: 58,
        changes: { photos: ago(40), intent: ago(200) },
      },
    },
    {
      id: 'aisha',
      name: 'Aisha',
      age: 27,
      gender: 'woman',
      place: P.delhi,
      profession: 'Architect',
      bio: 'Just moved back to Delhi after four years in Ahmedabad. Restoring old havelis, rediscovering the city, and looking for someone to explore it with.',
      intent: 'serious',
      lifestyle: ['Early riser', 'Social drinker', 'Cycles'],
      interests: ['Design', 'Travel', 'Photography', 'Music'],
      values: ['Curiosity', 'Honesty'],
      languages: ['Hindi', 'Urdu', 'English'],
      future: { marriageTimeline: 'In 2–3 years', children: 'Open to children' },
      verified: ['identity', 'photo', 'phone'],
      since: 5,
    },
    {
      id: 'meher',
      name: 'Meher',
      age: 29,
      gender: 'woman',
      place: P.gurgaon,
      profession: 'Corporate lawyer',
      bio: 'Long hours, longer reading list. I love old Bollywood, horse riding and the rare perfect cup of coffee.',
      intent: 'long-term',
      lifestyle: ['Night owl', 'Social drinker', 'Horse riding'],
      interests: ['Film', 'Reading', 'Travel'],
      values: ['Independence', 'Honesty'],
      languages: ['Hindi', 'Punjabi', 'English'],
      future: { marriageTimeline: 'In 1–2 years', children: 'Unsure about children' },
      verified: ['phone', 'photo', 'employment'],
      since: 70,
      history: {
        meaningfulInteractions: 4,
        mutualConnections: 3,
        completedConversations: 2,
        meetings: 1,
        durations: [9, 17],
        beyondInitialPct: 50,
        toMeetingPct: 33,
      },
    },
    {
      id: 'simran',
      name: 'Simran',
      age: 28,
      gender: 'woman',
      place: P.chandigarh,
      profession: 'School principal',
      bio: 'Youngest principal my school has had, and still the one who gets the most letters from students. Mountains every chance I get.',
      intent: 'marriage',
      lifestyle: ['Early riser', 'Vegetarian', 'Trekking'],
      interests: ['Trekking', 'Music', 'Cooking', 'Travel'],
      values: ['Family', 'Kindness'],
      languages: ['Punjabi', 'Hindi', 'English'],
      future: { marriageTimeline: 'In 1–2 years', children: 'Wants children', relocation: 'Open to relocating' },
      verified: ['identity', 'phone', 'photo', 'employment'],
      settings: { relocation: true, longDistance: true },
      since: 380,
      history: {
        meaningfulInteractions: 13,
        mutualConnections: 6,
        completedConversations: 5,
        meetings: 2,
        durations: [14, 30, 9, 21],
        beyondInitialPct: 72,
        toMeetingPct: 33,
      },
    },
    {
      id: 'tanvi',
      name: 'Tanvi',
      age: 31,
      gender: 'woman',
      place: P.jaipur,
      profession: 'Boutique hotelier',
      bio: 'I run a small heritage hotel my grandfather built. Hospitality is my love language, but I also need someone who can host me for a change.',
      intent: 'serious',
      lifestyle: ['Social drinker', 'Yoga'],
      interests: ['Food', 'Travel', 'Music', 'Design'],
      values: ['Family', 'Humour'],
      languages: ['Hindi', 'Marwari', 'English'],
      future: { marriageTimeline: 'In 2–3 years', children: 'Open to children' },
      plan: 'premium',
      verified: ['identity', 'phone', 'photo'],
      since: 210,
      history: {
        meaningfulInteractions: 9,
        mutualConnections: 4,
        completedConversations: 3,
        meetings: 2,
        durations: [18, 10, 26],
        beyondInitialPct: 60,
        toMeetingPct: 40,
      },
    },

    // ---- Discovery pool: national -----------------------------------------
    {
      id: 'ira',
      name: 'Ira',
      age: 29,
      gender: 'woman',
      place: P.bengaluru,
      profession: 'Data scientist',
      education: 'IISc Bangalore',
      bio: 'I build models that predict the weather and still forget my umbrella. Weekends are for climbing walls and long lunches.',
      intent: 'serious',
      intentNext: 'marriage',
      lifestyle: ['Climbs', 'Social drinker', 'Early riser'],
      interests: ['Climbing', 'Reading', 'Travel', 'Music'],
      values: ['Curiosity', 'Honesty'],
      languages: ['Hindi', 'Kannada', 'English'],
      future: { marriageTimeline: 'In 1–2 years', children: 'Wants children', relocation: 'Open to relocating' },
      openTo: ['romantic', 'friendship'],
      verified: ['identity', 'phone', 'photo', 'education'],
      settings: { longDistance: true, relocation: true, reach: 'national' },
      since: 260,
      history: {
        meaningfulInteractions: 10,
        mutualConnections: 5,
        completedConversations: 4,
        meetings: 2,
        durations: [12, 20, 7, 15],
        beyondInitialPct: 62,
        toMeetingPct: 40,
      },
    },
    {
      id: 'leela',
      name: 'Leela',
      age: 30,
      gender: 'woman',
      place: P.mumbai,
      profession: 'Film producer',
      bio: 'I make independent films and I am unreasonably good at finding the best vada pav in any neighbourhood.',
      intent: 'long-term',
      lifestyle: ['Night owl', 'Social drinker'],
      interests: ['Film', 'Food', 'Travel', 'Music'],
      values: ['Humour', 'Independence'],
      languages: ['Hindi', 'Marathi', 'English'],
      future: { children: 'Open to children', relocation: 'Open to relocating' },
      verified: ['phone', 'photo', 'employment'],
      settings: { relocation: true },
      since: 150,
      history: { meaningfulInteractions: 5, mutualConnections: 3, completedConversations: 2, meetings: 1, durations: [8, 14] },
    },

    // ---- Discovery pool: international ------------------------------------
    {
      id: 'maya',
      name: 'Maya',
      age: 31,
      gender: 'woman',
      place: P.toronto,
      profession: 'Family physician',
      bio: 'Born in Pune, raised in Toronto. I’ve been thinking about moving closer to family in India, and I’d rather find the right person than the right city.',
      intent: 'marriage',
      lifestyle: ['Early riser', 'Runs', 'Vegetarian'],
      interests: ['Running', 'Reading', 'Travel', 'Cooking'],
      values: ['Family', 'Honesty', 'Kindness'],
      languages: ['Marathi', 'Hindi', 'English', 'French'],
      future: { marriageTimeline: 'In 1–2 years', children: 'Wants children', relocation: 'Open to relocating' },
      plan: 'premium',
      verified: ['identity', 'phone', 'photo', 'employment', 'education'],
      settings: { international: true, relocation: true, longDistance: true, reach: 'global' },
      since: 330,
      history: {
        meaningfulInteractions: 12,
        mutualConnections: 6,
        completedConversations: 5,
        meetings: 2,
        durations: [22, 35, 10, 16],
        beyondInitialPct: 70,
        toMeetingPct: 33,
      },
    },
    {
      id: 'diya',
      name: 'Diya',
      age: 28,
      gender: 'woman',
      place: P.dubai,
      profession: 'Brand strategist',
      bio: 'Dubai for work, Delhi for heart. I love desert drives, loud family dinners and a good argument about typography.',
      intent: 'serious',
      lifestyle: ['Social drinker', 'Gym'],
      interests: ['Design', 'Travel', 'Music'],
      values: ['Humour', 'Family'],
      languages: ['Hindi', 'English', 'Arabic'],
      future: { marriageTimeline: 'In 2–3 years', relocation: 'Open to relocating' },
      verified: ['phone', 'photo'],
      settings: { international: true, relocation: true },
      since: 25,
    },
    {
      id: 'naina',
      name: 'Naina',
      age: 30,
      gender: 'woman',
      place: P.singapore,
      profession: 'Investment analyst',
      bio: 'Numbers person with a soft spot for poetry. Six years in Singapore, still hunting for proper chaat.',
      intent: 'long-term',
      lifestyle: ['Early riser', 'Swims'],
      interests: ['Poetry', 'Swimming', 'Travel', 'Reading'],
      values: ['Honesty', 'Independence'],
      languages: ['Hindi', 'English', 'Gujarati'],
      future: { children: 'Open to children', relocation: 'Open to relocating' },
      verified: ['identity', 'phone', 'photo', 'employment'],
      settings: { international: true, relocation: true },
      since: 190,
      history: { meaningfulInteractions: 6, mutualConnections: 3, completedConversations: 2, meetings: 1, durations: [11, 19, 5] },
    },
    {
      id: 'sofia',
      name: 'Sofia',
      age: 29,
      gender: 'woman',
      place: P.lisbon,
      profession: 'Marine biologist',
      bio: 'Portuguese, spent two years researching coral off the Andaman coast and fell in love with India. Still dreaming in Hindi, badly.',
      intent: 'exploring',
      lifestyle: ['Swims', 'Social drinker', 'Early riser'],
      interests: ['Diving', 'Travel', 'Music', 'Reading'],
      values: ['Curiosity', 'Kindness'],
      languages: ['Portuguese', 'English', 'Hindi'],
      verified: ['identity', 'phone', 'photo'],
      settings: { international: true, relocation: true },
      since: 95,
      history: { meaningfulInteractions: 3, mutualConnections: 2, completedConversations: 1, durations: [13] },
    },

    // ---- Friendship pool (NCR) --------------------------------------------
    {
      id: 'arjun',
      name: 'Arjun',
      age: 33,
      gender: 'man',
      place: P.gurgaon,
      profession: 'Chef & restaurateur',
      bio: 'Runs a small kitchen in Sector 29. Looking for people who like to eat, walk, and talk about both.',
      intent: 'friendship',
      lifestyle: ['Night owl', 'Runs on weekends'],
      interests: ['Food', 'Running', 'Music', 'Cooking'],
      values: ['Loyalty', 'Humour'],
      languages: ['Hindi', 'English'],
      openTo: ['friendship'],
      verified: ['identity', 'phone', 'photo'],
      since: 180,
      history: { meaningfulInteractions: 7, mutualConnections: 4, completedConversations: 3, meetings: 3, durations: [40, 22, 60] },
    },
    {
      id: 'farah',
      name: 'Farah',
      age: 28,
      gender: 'woman',
      place: P.gurgaon,
      profession: 'Bookshop owner',
      bio: 'I own a tiny bookshop and host a monthly reading circle. Always looking for new regulars and new friends.',
      intent: 'friendship',
      lifestyle: ['Early riser', 'Doesn’t drink'],
      interests: ['Reading', 'Music', 'Theatre'],
      values: ['Kindness', 'Curiosity'],
      languages: ['Hindi', 'Urdu', 'English'],
      openTo: ['friendship'],
      verified: ['phone', 'photo'],
      since: 110,
      history: { meaningfulInteractions: 4, mutualConnections: 3, completedConversations: 2, meetings: 2, durations: [15, 30] },
    },
    {
      id: 'dev',
      name: 'Dev',
      age: 29,
      gender: 'man',
      place: P.delhi,
      profession: 'Classical musician',
      bio: 'Sitar player. Teaches kids on weekdays, plays small concerts on weekends. Would love a friend who likes long walks and longer conversations.',
      intent: 'friendship',
      lifestyle: ['Early riser', 'Vegetarian'],
      interests: ['Music', 'Travel', 'Reading'],
      values: ['Curiosity', 'Kindness'],
      languages: ['Hindi', 'English'],
      openTo: ['friendship'],
      verified: ['identity', 'phone', 'photo'],
      since: 240,
      history: { meaningfulInteractions: 6, mutualConnections: 3, completedConversations: 3, meetings: 2, durations: [21, 34, 16] },
    },

    // ---- Meera's world (Bengaluru & South India) --------------------------
    {
      id: 'rohan',
      name: 'Rohan',
      age: 29,
      gender: 'man',
      place: P.bengaluru,
      profession: 'Product manager',
      education: 'BITS Pilani',
      bio: 'I build software for farmers and spend weekends trying to grow tomatoes on my balcony (0 for 3 so far). Big on theatre, small on small talk.',
      intent: 'long-term',
      lifestyle: ['Early riser', 'Doesn’t drink', 'Yoga'],
      interests: ['Theatre', 'Gardening', 'Reading', 'Hiking'],
      values: ['Kindness', 'Honesty'],
      languages: ['Kannada', 'Hindi', 'English'],
      future: { marriageTimeline: 'In 2–3 years', children: 'Open to children', family: 'Close to family, independent household' },
      verified: ['identity', 'phone', 'photo', 'employment'],
      since: 230,
      history: {
        meaningfulInteractions: 9,
        mutualConnections: 5,
        completedConversations: 4,
        meetings: 2,
        movedToFriendship: 1,
        durations: [17, 9, 28, 13],
        beyondInitialPct: 70,
        toMeetingPct: 40,
      },
    },
    {
      id: 'aditya',
      name: 'Aditya',
      age: 30,
      gender: 'man',
      place: P.bengaluru,
      profession: 'Cardiologist',
      bio: 'I fix hearts professionally and I am terrible at it personally — let’s see if that changes. Filter coffee and old Kannada songs.',
      intent: 'long-term',
      intentNext: 'marriage',
      lifestyle: ['Early riser', 'Runs', 'Doesn’t drink'],
      interests: ['Reading', 'Music', 'Hiking', 'Coffee'],
      values: ['Kindness', 'Family'],
      languages: ['Kannada', 'English'],
      future: { marriageTimeline: 'In 2–3 years', children: 'Open to children' },
      plan: 'premium',
      verified: ['identity', 'phone', 'photo', 'employment', 'education'],
      since: 410,
      history: {
        meaningfulInteractions: 15,
        mutualConnections: 8,
        completedConversations: 6,
        meetings: 3,
        durations: [20, 12, 33, 9, 15],
        beyondInitialPct: 73,
        toMeetingPct: 37,
      },
    },
    {
      id: 'karan',
      name: 'Karan',
      age: 28,
      gender: 'man',
      place: P.bengaluru,
      profession: 'Sound engineer',
      bio: 'I record indie bands in a studio in Indiranagar. Will make you a playlist within the first week, sorry in advance.',
      intent: 'exploring',
      lifestyle: ['Night owl', 'Social drinker'],
      interests: ['Music', 'Theatre', 'Coffee'],
      values: ['Humour', 'Curiosity'],
      languages: ['Hindi', 'English'],
      verified: ['phone'],
      since: 12,
    },
    {
      id: 'vikram',
      name: 'Vikram',
      age: 31,
      gender: 'man',
      place: P.bengaluru,
      profession: 'Founder, climate startup',
      bio: 'Building batteries that don’t cost the earth. I cook elaborate Sunday lunches and read everything by Amitav Ghosh.',
      intent: 'serious',
      lifestyle: ['Early riser', 'Cycles', 'Social drinker'],
      interests: ['Reading', 'Cooking', 'Hiking', 'Travel'],
      values: ['Curiosity', 'Independence'],
      languages: ['Tamil', 'English'],
      future: { marriageTimeline: 'In 2–3 years', children: 'Open to children', relocation: 'Open to relocating' },
      plan: 'premium',
      verified: ['identity', 'phone', 'photo', 'employment'],
      settings: { international: true, relocation: true },
      since: 520,
      history: {
        meaningfulInteractions: 21,
        mutualConnections: 10,
        completedConversations: 8,
        meetings: 4,
        movedToFriendship: 2,
        durations: [11, 26, 8, 19, 14, 30],
        beyondInitialPct: 69,
        toMeetingPct: 40,
      },
    },
    {
      id: 'nikhil',
      name: 'Nikhil',
      age: 27,
      gender: 'man',
      place: P.bengaluru,
      profession: 'Primary school teacher',
      bio: 'I teach nine-year-olds maths and they teach me patience. Weekend treks, weekday crosswords.',
      intent: 'long-term',
      lifestyle: ['Early riser', 'Doesn’t drink', 'Trekking'],
      interests: ['Hiking', 'Reading', 'Board games'],
      values: ['Kindness', 'Honesty'],
      languages: ['Kannada', 'Tamil', 'English'],
      future: { children: 'Wants children' },
      verified: ['phone', 'photo'],
      since: 55,
      history: { meaningfulInteractions: 3, mutualConnections: 2, completedConversations: 1, durations: [10] },
    },
    {
      id: 'siddharth',
      name: 'Siddharth',
      age: 30,
      gender: 'man',
      place: P.mysuru,
      profession: 'Conservation architect',
      bio: 'Restoring palaces in Mysuru and very happy to give you a tour. Yoga every morning, bad puns every evening.',
      intent: 'long-term',
      lifestyle: ['Early riser', 'Yoga', 'Vegetarian'],
      interests: ['Design', 'Reading', 'Theatre'],
      values: ['Curiosity', 'Family'],
      languages: ['Kannada', 'English'],
      verified: ['identity', 'phone', 'photo'],
      settings: { relocation: true },
      since: 170,
      history: { meaningfulInteractions: 5, mutualConnections: 3, completedConversations: 2, meetings: 1, durations: [16, 12] },
    },
    {
      id: 'anika',
      name: 'Anika',
      age: 26,
      gender: 'woman',
      place: P.bengaluru,
      profession: 'Illustrator',
      bio: 'Moved to Bengaluru six months ago and would love a friend for gallery walks and cheap dosa.',
      intent: 'friendship',
      lifestyle: ['Night owl', 'Pet lover'],
      interests: ['Art', 'Reading', 'Coffee', 'Theatre'],
      values: ['Kindness', 'Curiosity'],
      languages: ['Hindi', 'English'],
      openTo: ['friendship'],
      verified: ['phone', 'photo'],
      since: 30,
    },

    // ---- Sarah's world (London & international) ---------------------------
    {
      id: 'rehan',
      name: 'Rehan',
      age: 32,
      gender: 'man',
      place: P.london,
      profession: 'NHS surgeon',
      bio: 'British-Indian, raised in Leicester, obsessed with cricket and my mum’s biryani. I want the kind of marriage my grandparents had — with better communication.',
      intent: 'serious',
      lifestyle: ['Early riser', 'Plays cricket', 'Doesn’t drink'],
      interests: ['Cricket', 'Travel', 'Music', 'Cooking'],
      values: ['Family', 'Honesty'],
      languages: ['English', 'Urdu', 'Hindi'],
      future: { marriageTimeline: 'In 1–2 years', children: 'Wants children' },
      verified: ['identity', 'phone', 'photo', 'employment'],
      settings: { international: true },
      since: 280,
      history: { meaningfulInteractions: 10, mutualConnections: 5, completedConversations: 4, meetings: 3, durations: [21, 13, 30, 9] },
    },
    {
      id: 'theo',
      name: 'Theo',
      age: 30,
      gender: 'man',
      place: P.london,
      profession: 'Novelist',
      bio: 'Second novel out next spring. Swims in the Hampstead ponds year-round, which tells you most of what you need to know.',
      intent: 'long-term',
      lifestyle: ['Swims', 'Social drinker', 'Cycles to work'],
      interests: ['Reading', 'Swimming', 'Design', 'Travel'],
      values: ['Humour', 'Curiosity'],
      languages: ['English', 'French'],
      future: { children: 'Open to children' },
      verified: ['phone', 'photo'],
      since: 40,
      history: { meaningfulInteractions: 2, mutualConnections: 1 },
    },
  ];
  return specs.map((sp) => person(sp, now));
}

// ---------------------------------------------------------------------------
// Feedback generator (fictional aggregated history)
// ---------------------------------------------------------------------------

const POSITIVE_COMMENTS: Record<string, string[]> = {
  ananya: [
    'Very respectful and easy to talk to.',
    'Clear about intentions and easy to communicate with.',
    'We weren’t compatible romantically, but she handled the conversation maturely.',
    'Kind, thoughtful, and honest when it mattered.',
  ],
  priya: [
    'Straightforward and warm. Always did what she said she would.',
    'Easy conversations and very clear about what she wanted.',
  ],
  neha: ['Busy schedule but always communicated honestly about it.', 'Genuine and very kind.'],
  kavya: [
    'Thoughtful and grounded. It didn’t work out, but it was a lovely experience.',
    'Very respectful of boundaries and clear from day one.',
    'We met twice — she was exactly who her profile said she was.',
  ],
  abhishek: [
    'Respectful and genuinely interested in the conversation.',
    'Clear about where he was and what he wanted. Appreciated the honesty.',
    'We decided we were better as friends — he handled it well.',
  ],
  vikram: ['Honest and considerate, even when closing things.', 'Great conversations; always on time.'],
  aditya: ['Warm, patient and clear.', 'Very respectful — a good experience even though it ended.'],
  rahul: ['Great company and reliable.'],
  tara: ['Slow to reply but wonderful company in person.', 'Genuine and fun.'],
  simran: ['Kind and clear about her intentions.'],
  rehan: ['Considerate and clear. Good experience.'],
  maya: ['Honest about the distance from day one. Appreciated that.'],
};

function generateFeedback(
  about: string,
  n: number,
  rates: Partial<Record<Trait, number>>,
  now: number,
): FeedbackEntry[] {
  const comments = POSITIVE_COMMENTS[about] ?? [];
  return Array.from({ length: n }, (_, i) => {
    const traits = Object.fromEntries(
      TRAITS.map((t) => [t, i < Math.round((rates[t] ?? 0.92) * n)]),
    ) as Record<Trait, boolean>;
    return {
      id: `f_${about}_${i}`,
      about,
      author: `former_${about}_${i}`,
      traits,
      comment: comments[i],
      at: new Date(now - (20 + i * 23) * DAY).toISOString(),
      status: 'published' as const,
    };
  });
}

// ---------------------------------------------------------------------------
// Connections
// ---------------------------------------------------------------------------

function conn(
  id: string,
  a: string,
  b: string,
  kind: Kind,
  status: Connection['status'],
  mutualDaysAgo: number,
  now: number,
  extra: Partial<Connection> = {},
): Connection {
  return {
    id,
    users: [a, b],
    kind,
    status,
    mutualAt: new Date(now - mutualDaysAgo * DAY).toISOString(),
    stagesReached: [],
    messages: [],
    meetingReady: {},
    checkins: {},
    feedbackDue: [],
    ...extra,
  };
}

function thread(now: number, startDaysAgo: number, lines: [string, string][]): Message[] {
  const start = now - startDaysAgo * DAY;
  const step = (startDaysAgo * DAY) / (lines.length + 1);
  return lines.map(([from, text], i) => ({
    id: `m_seed_${startDaysAgo}_${i}`,
    from,
    text,
    at: new Date(start + step * (i + 1)).toISOString(),
    kind: from === 'system' ? 'system' : 'text',
  }));
}

// ---------------------------------------------------------------------------
// Assemble
// ---------------------------------------------------------------------------

export function createSeedState(nowMs = Date.now()): State {
  const now = nowMs;
  const ago = (d: number) => new Date(now - d * DAY).toISOString();
  const users = Object.fromEntries(people(now).map((u) => [u.id, u]));

  const connections: Connection[] = [
    conn('c_ananya', 'abhishek', 'ananya', 'romantic', 'primary', 15, now, {
      primarySince: ago(12),
      stagesReached: ['primary', 'conversation', 'voice'],
      messages: thread(now, 12, [
        ['system', "You're now each other's Primary connection. Take your time."],
        ['ananya', 'Okay, I have to ask — is the rajma story in your profile true? Did you actually call your mother mid-recipe?'],
        ['abhishek', 'Twice. She now sends me voice notes preemptively every Sunday.'],
        ['ananya', 'That’s adorable. My nani does the same with fish curry. I still get it wrong.'],
        ['abhishek', 'We should compare disasters sometime. I’m free for a call this weekend if you are?'],
        ['ananya', 'Saturday evening works. And I loved the call last night, by the way. I didn’t expect to talk for two hours.'],
        ['abhishek', 'Me neither. It felt easy. Talk Saturday?'],
        ['ananya', 'Saturday ☺️'],
      ]),
    }),
    conn('c_rahul', 'abhishek', 'rahul', 'friendship', 'primary', 10, now, {
      primarySince: ago(8),
      stagesReached: ['primary', 'conversation', 'meeting'],
      messages: thread(now, 8, [
        ['system', "You're now each other's Primary friend."],
        ['rahul', 'Karim’s on Saturday? I’ll bring a friend’s cricket bat for the park after.'],
        ['abhishek', 'Deal. I haven’t batted in ten years, lower your expectations.'],
        ['rahul', 'Already on the floor. 1pm at Jama Masjid gate 1.'],
      ]),
    }),
    conn('c_neha', 'abhishek', 'neha', 'romantic', 'mutual', 6, now),
    conn('c_priya', 'abhishek', 'priya', 'romantic', 'mutual', 4, now, { invite: { by: 'priya', at: ago(1) } }),
    conn('c_riya', 'abhishek', 'riya', 'romantic', 'mutual', 2, now),
    conn('c_sarah', 'abhishek', 'sarah', 'romantic', 'mutual', 1, now),
    conn('c_kabir', 'abhishek', 'kabir', 'friendship', 'mutual', 5, now),
    conn('c_tara', 'abhishek', 'tara', 'friendship', 'mutual', 3, now, {
      fromRomance: true,
      stagesReached: ['primary', 'conversation', 'meeting'],
      messages: thread(now, 40, [
        ['system', 'You both chose friendship. Your romantic slots are free; this friendship continues.'],
        ['tara', 'For the record, this is the nicest way anything has ever ended for me. Friends for real?'],
        ['abhishek', 'Friends for real. You still owe me that jazz bar.'],
      ]),
    }),
    conn('c_ishaan', 'abhishek', 'ishaan', 'friendship', 'mutual', 1, now),
    conn('c_mansi', 'abhishek', 'mansi', 'romantic', 'closed', 40, now, {
      primarySince: ago(30),
      stagesReached: ['primary', 'conversation', 'voice', 'meeting'],
      closure: { by: 'mansi', reason: "Our long-term goals don't align.", note: 'I really enjoyed our conversations. I think we want different cities in the long run. Wishing you the best.', at: ago(3) },
      feedbackDue: ['abhishek'],
    }),
    // Meera
    conn('c_rohan', 'meera', 'rohan', 'romantic', 'mutual', 1, now),
  ];

  const interests: Interest[] = [];
  const addInterest = (from: string, to: string, kind: Kind, d: number) =>
    interests.push({ from, to, kind, at: ago(d) });
  for (const c of connections) {
    addInterest(c.users[0], c.users[1], c.kind === 'friendship' && c.fromRomance ? 'romantic' : c.kind, 20);
    addInterest(c.users[1], c.users[0], c.kind === 'friendship' && c.fromRomance ? 'romantic' : c.kind, 20);
  }
  // People who have already chosen a persona — expressing interest back creates mutual interest.
  addInterest('kavya', 'abhishek', 'romantic', 2);
  addInterest('ira', 'abhishek', 'romantic', 3);
  addInterest('maya', 'abhishek', 'romantic', 1);
  addInterest('arjun', 'abhishek', 'friendship', 2);
  addInterest('aditya', 'meera', 'romantic', 1);
  addInterest('vikram', 'meera', 'romantic', 4);
  addInterest('anika', 'meera', 'friendship', 2);
  addInterest('rehan', 'sarah', 'romantic', 2);

  const feedback: FeedbackEntry[] = [
    ...generateFeedback('ananya', 18, { respect: 1, communication: 0.89, authenticity: 0.94, responsiveness: 0.83, reliability: 0.89, clarity: 0.94, overall: 0.94 }, now),
    ...generateFeedback('priya', 7, { respect: 1, communication: 0.86, reliability: 1, clarity: 1, overall: 0.86 }, now),
    ...generateFeedback('neha', 6, { responsiveness: 0.67, reliability: 0.83 }, now),
    ...generateFeedback('kavya', 9, { respect: 1, communication: 0.89, authenticity: 1, overall: 0.89 }, now),
    ...generateFeedback('abhishek', 8, { respect: 1, communication: 0.88, reliability: 0.88, responsiveness: 0.75, overall: 0.88 }, now),
    ...generateFeedback('vikram', 7, {}, now),
    ...generateFeedback('aditya', 6, {}, now),
    ...generateFeedback('rahul', 5, {}, now),
    ...generateFeedback('tara', 5, { responsiveness: 0.4 }, now),
    ...generateFeedback('simran', 5, {}, now),
    ...generateFeedback('rehan', 5, {}, now),
    ...generateFeedback('maya', 6, {}, now),
    ...generateFeedback('riya', 2, {}, now),
    ...generateFeedback('sarah', 3, {}, now),
    ...generateFeedback('meher', 3, {}, now),
    ...generateFeedback('rohan', 4, {}, now),
    // Mansi has already left hers about Abhishek; it's held until he submits (double-blind).
    {
      id: 'f_mansi_abhishek',
      about: 'abhishek',
      author: 'mansi',
      connectionId: 'c_mansi',
      traits: { respect: true, communication: true, authenticity: true, responsiveness: true, reliability: true, clarity: true, overall: true },
      comment: 'Warm and honest. We just want different things long-term.',
      at: ago(2),
      status: 'awaiting-release',
    },
    // A reported item waiting in the Trust & Safety queue.
    {
      id: 'f_reported_demo',
      about: 'neha',
      author: 'former_neha_x',
      traits: { respect: false, communication: false, authenticity: false, responsiveness: false, reliability: false, clarity: false, overall: false },
      comment: 'Total scammer, stay away from her. She lives at Bandra West.',
      at: ago(4),
      status: 'held',
    },
  ];

  const notices: State['notices'] = [
    { id: 'n1', for: 'abhishek', text: 'Your Primary connection sent you a message.', at: ago(0.2), read: false, link: '/chat/c_ananya' },
    { id: 'n2', for: 'abhishek', text: 'Priya would like to make your connection Primary whenever you’re ready.', at: ago(1), read: false, link: '/connections?kind=romantic' },
    { id: 'n3', for: 'abhishek', text: 'You have mutual interest with Sarah.', at: ago(1), read: true, link: '/connections?kind=romantic' },
    { id: 'n4', for: 'abhishek', text: 'Mansi closed your connection respectfully and shared why.', at: ago(3), read: true, link: '/chat/c_mansi' },
    { id: 'n5', for: 'meera', text: 'You have mutual interest with Rohan.', at: ago(1), read: false, link: '/connections?kind=romantic' },
    { id: 'n6', for: 'sarah', text: 'You have mutual interest with Abhishek.', at: ago(1), read: false, link: '/connections?kind=romantic' },
  ];

  return {
    version: STATE_VERSION,
    now: new Date(now).toISOString(),
    day: 0,
    viewerId: 'abhishek',
    onboarded: false,
    offline: false,
    users,
    interests,
    passes: [],
    connections,
    feedback,
    notices,
    visits: [
      { from: 'kavya', to: 'abhishek', at: ago(1) },
      { from: 'aisha', to: 'abhishek', at: ago(2) },
      { from: 'aditya', to: 'meera', at: ago(0.5) },
      { from: 'rehan', to: 'sarah', at: ago(3) },
    ],
    discovery: {},
  };
}

export const PERSONAS = ['abhishek', 'meera', 'sarah'];
